# version: '3.8'

services:
  backend:
    build:
      context: ./Final_back
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    env_file:
      - .env
    networks:
      - dev-network
    depends_on:
      - db

  frontend:
    build:
      context: ./Final_front
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    env_file:
      - .env
    networks:
      - dev-network
    depends_on:
      - backend

  ml:
    build:
      context: ./Final_ml
    ports:
      - "${ML_PORT:-8000}:8000"
    env_file:
      - .env
    networks:
      - dev-network
    depends_on:
      - backend
    
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mongeul
      MYSQL_USER: TEST
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  db_data: