# .github/workflows/ci.yml

name: CI for final-project

# 우선 main에 push(submodule commit update)될때마다 실행되도록 설정
on: 
  push: 
    branches:
      - setting/action 
      # - main 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
        #   password: ${{ secrets.EC2_PASSWORD }}
          script: |
            cd dev/final-project-production/
            echo "Before update:"
            # git submodule status
            # git submodule update --remote
            # echo "After update:"
            # git submodule status